vm   = Amazon-Linux-2
vbox = VBoxManage
port = 2222
key  = ../vagrant.key
iso  = /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso

.PHONY : startvm

#startvm : vboxguestadditions
#	$(vbox) startvm $(vm) --type headless || exit 0

#ssh:
#	ssh vagrant@127.0.0.1 -p $(port) -i $(key) 'df -h'

#vboxguestadditions:
#	$(vbox) storageattach $(vm) --storagectl IDE --port 0 --device 0 --type dvddrive --medium emptydrive
#	$(vbox) storageattach $(vm) --storagectl IDE --port 0 --device 0 --type dvddrive --medium $(iso)

#clean:
#	$(vbox) controlvm $(vm) acpipowerbutton || exit 0

